version: ImageMagick-{branch}.{build}

os: Windows Server 2012 R2

clone_folder: C:\ImageMagick
shallow_clone: true

skip_tags: true

matrix:
  fast_finish: true

cache:
  - C:\Strawberry-x86 -> AppVeyor\Install.cmd
  - C:\Strawberry-x64 -> AppVeyor\Install.cmd
  - C:\InnoSetup -> AppVeyor\Install.cmd

environment:

  matrix:
    - im_platform: "x64"
      im_name:     "dll-Q8"
    - im_platform: "x64"
      im_name:     "dll-Q16"
    - im_platform: "x64"
      im_name:     "static-Q8"
    - im_platform: "x64"
      im_name:     "static-Q16"

    - im_platform: "x86"
      im_name:     "dll-Q8"
    - im_platform: "x86"
      im_name:     "dll-Q16"
    - im_platform: "x86"
      im_name:     "static-Q8"
    - im_platform: "x86"
      im_name:     "static-Q16"

    - im_platform: "x64"
      im_name:     "hdri-dll-Q16"
    - im_platform: "x64"
      im_name:     "hdri-static-Q16"

    - im_platform: "x86"
      im_name:     "hdri-dll-Q16"
    - im_platform: "x86"
      im_name:     "hdri-static-Q16"

    - im_platform: "x64"
      im_name:     "portable-Q16"
    - im_platform: "x86"
      im_name:     "portable-Q16"

    - im_platform: "none"
      im_name:     "source"

install:
  - cd AppVeyor
  - Install.cmd %im_platform%

artifacts:
  - path: 'Windows-Distribution\*.exe'
  - path: 'Windows-Distribution\*.zip'
  - path: 'Windows-Distribution\Version.txt'

build_script:
  - cd AppVeyor
  - Build.cmd %im_platform% %im_name%

test: off

deploy:
  provider: FTP
  protocol: ftp
  host: magick.imagemagick.org
  folder: /ImageMagick-6
  username: upload
  password:
    secure: 5jIgwMyyjTcIfLY/Xqk7dg==
  beta: true

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
